### ISSUE TITLE
Probably not an issue with OpenScraping, but for your awareness...

### ISSUE THREAD

**Issue by pldmgg** [microsoft/openscraping-lib-csharp#11]
I'm trying to use OpenScraping in a CSharp Script .csx using dotnet-script (https://github.com/filipw/dotnet-script). I posted an issue over there, but wanted to also submit here on the off chance that you'd be interested and/or possibly have some advice.

https://github.com/filipw/dotnet-script/issues/114

**Comment by zmarty** [comment]
Thanks for letting me know! I read the referenced item. Please keep me posted if you find anything.

The way I tested the new package is in VS 2017 I created a separate .NET 2.0 project, then referenced the NuGet package, and wrote some simple parsing tests. And it worked.

**Comment by pldmgg** [comment]
Oh yeah, it works great in a VS 2017 .Net Core 2.0 App. Hopefully I can figure out the issue with either dotnet-script or my environment around dotnet-script (right now I'm leaning more towards something wrong with my environment since the dotnet-script netcoreapp2.0 feature branch gives me the exact same error as the netcoreapp1.1 version of dotnet-script...)

**Comment by pldmgg** [comment]
Finally got it working with the dotnet-script feature branch. Full details here:

https://github.com/filipw/dotnet-script/issues/114#issuecomment-326280083

**Comment by zmarty** [comment]
Thanks!
