### ISSUE TITLE
Incompatibility with .Net Standard 2.0

### ISSUE THREAD

**Issue by colinthompson** [microsoft/openscraping-lib-csharp#12]
When trying to add this package to a project targeting .NET standard 2.0, an error is thrown because OpenScraping v1.0.1 only supports netcoreapp2.0.

Here is the output when running `dotnet add OpenScraping`:
```
info :   GET https://api.nuget.org/v3-flatcontainer/openscraping/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/openscraping/index.json 380ms
error: Package OpenScraping 1.0.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package OpenScraping 1.0.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
error: Package 'OpenScraping' is incompatible with 'all' frameworks in project '<REDACTED>/Project.csproj'.
```

**Comment by zmarty** [comment]
I am still navigating the differences between them, but as you noticed the library currently supports .Net Core, not .Net Standard.

**Comment by willadsen** [comment]
@colinthompson  I've create a PR, #15 which hopefully will be merged soon

**Comment by colinthompson** [comment]
Thanks! Looking forward to it.

**Comment by zmarty** [comment]
Thank you Andreas, this is now in master.
