### ISSUE TITLE
Missing extra spaces in RemoveExtraWhitespaceTransformation example

### ISSUE THREAD

**Issue by jwatkin** [microsoft/openscraping-lib-csharp#17]
In the documentation for [Transformations](https://github.com/Microsoft/openscraping-lib-csharp#transformations), the **RemoveExtraWhitespaceTransformation** example doesn't display the extra spaces in the first occurrence of "hello world". I think you'll need to use non-breaking spaces there, or if that doesn't work something else that has the same effect as non-breaking spaces.

It looks like this:
> Replaces consecutive spaces with a single space. For the string "hello     world" it would return "hello world".

But it should look like this:
> Replaces consecutive spaces with a single space. For the string "hello&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;world" it would return "hello world".

**Comment by zmarty** [comment]
Thank you!
