### ISSUE TITLE
Regex Transformation not returning first match

### ISSUE THREAD

**Issue by Sebbl22** [microsoft/openscraping-lib-csharp#24]
Hello, I am using this config 
```
{
  "id": {
    "_xpath": "//link[@rel='canonical']/@href",
    "_transformations": [
      {
        "_type": "RegexTransformation",
        "_regex": "[0-9]{7}$"
      }
    ]
  }
}
```
to extract from this document
```
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
   <meta charset="utf-8" />
   <link rel="canonical" href="http://example.com/test-xyz-1234567" />
    <title>Test</title>
</head>
<body>
    Test
</body>
</html>
```
My goal is to extract "1234567" from the link-tag.

The resulting output is empty.
Reason: In RegexTransformation.cs the first match is ignored ([line 77](https://github.com/Microsoft/openscraping-lib-csharp/blob/915ffdc66c040ea18c7688f0cb36cf67c61cb381/OpenScraping/Transformations/RegexTransformation.cs#L77)).

I am not sure why the first match is ignored and how to work around this in my example.
Could someone please provide some advice? Thank you very much.

**Comment by zmarty** [comment]
I have seen your question but did not have time to look into it yet. If it's a bug I will fix it and add a test case.

**Comment by Sebbl22** [comment]
Thanks. I investigated further and it seems that all the existing examples and test cases use regex capture groups. Thats why there's always a "Full match" group and at least one additional group.
I will alter my regex to `([0-9]{7})$`. As it uses a capture group now, it works just fine.

But I think it is not correct to remove the "Full match" group, since the regex matches to this group too. Unfortunately it would be a breaking change.

**Comment by zmarty** [comment]
Thanks. I will close this for now. I remember there was a problem with full match groups that is why they are not supported, can't remember what.
