### ISSUE TITLE
Using "_xpath" on table with one row does not create an JSON array

### ISSUE THREAD

**Issue by FrederickBrier** [microsoft/openscraping-lib-csharp#25]
The _xpath feature seems to behave differently if there is only one result from the _xpath. It will generate:

"rows": { "col1": "val1", "col2": "val2" }

Instead of:

"rows": [{ "col1": "val1", "col2": "val2" }]

This makes it difficult to iterate over the array of rows, as you end up iterating over the columns. Thoughts? Is there a way to force it to be an array regardless of there being a single row? Thank you.

**Comment by PoLaKoSz** [comment]
~This is the first day i use this library but i don't think there is a nice way to solve our problem.~ (https://github.com/microsoft/openscraping-lib-csharp/issues/25#issuecomment-564819933)
I came up with this simple fix (just wrap the `JObject` with a `JArray` ):

``` c#
// ... 
JContainer scrapingResults = openScraping.Extract(html);
if (scrapingResults["row"].GetType() == typeof(JObject))
{
    JArray container = new JArray
    {
        scrapingResults["row"]
    };
    scrapingResults["row"] = container;
}
Console.WriteLine(JsonConvert.SerializeObject(scrapingResults, Formatting.Indented));
```

**Comment by zmarty** [comment]
Did you try to use _forceArray option?

**Comment by zmarty** [comment]
Something like this:
```javascript
"title":
{
    "_xpath": "//h1",
    "_forceArray": true
}
```

**Comment by PoLaKoSz** [comment]
Thank You! It works like a charm. :smile:
