### ISSUE TITLE
Regexp Transformation

### ISSUE THREAD

**Issue by agabuza** [microsoft/openscraping-lib-csharp#8]
While using openscraping faced quite common scenario when a specific subset(word) has to be selected from element with plain text. 

Sample: `<div class="info">Contact information. Phone: 111-111-111, Address: str.Street 1/1, City. 2017</div>`

Would be really useful to have built-in `RegexpTransformation `which can take custom regexp expressions as an input param '_regexp'. Something like '_separator' in `SplitTransformation`.

**Comment by zmarty** [comment]
Thanks, I think this is a good idea.

**Comment by zmarty** [comment]
#20 This is now implemented and will go out on NuGet in a few minutes, thanks for the suggestion.
