### ISSUE TITLE
Get meta data?

### ISSUE THREAD

**Issue by TJF0700** [microsoft/openscraping-lib-csharp#9]
I have a need to get the content of meta data - how is this possible?
`  <meta content="Tim Fischer" name="author">`

Thanks

**Comment by zmarty** [comment]
How about:
//meta[@name='author']/content

**Comment by TJF0700** [comment]
That didn't work:
I tried: `//meta[@name='author']/content`  and `//meta[@name='author']/@content`

With the @ sign, I get a null "author", but without the @ sign, there isn't a returned json field at all.

**Comment by TJF0700** [comment]
Ok - the code only accounts for the innerHtml - thinking that if the last element in the xpath query has an @ sign, go for the attribute data instead.... thoughts?

**Comment by zmarty** [comment]
Yes, see here for the problem and a workaround: https://github.com/Microsoft/openscraping-lib-csharp/issues/6

I did not have time to implement an official fix yet.
